#! /usr/bin/env bash

push=$1

models="distil-whisper/distil-large-v3"
base_tags="latest latest-fa2"

./build $push
./build --flash-attention-2 $push

for model in $models; do
  for base_tag in $base_tags; do
    ./build-baked --model $model --base-tag $base_tag $push
  done
done
